// src/lib/components/sections/Footer.svelte
<script>
	import Icon from '@iconify/svelte';
</script>

<footer
	class="h-[300px] flex flex-col justify-center items-center mt-[150px] bg-black dark:bg-darkSmoke text-white"
>
	<div class="mx-auto px-[16px]">
		<p class="font-bold">Copyright © Sean Redmon</p>
		<p>Thanks to my close friend and colleague 纪丽瑶</p>
		<p class="underline mt-[32px]">Previous versions</p>
		<ul class="text-[14px]">
			<li>
				<a class="hover:opacity-75" href="https://seanred-v-1-1-3-reactversion.netlify.app/"
					><span>V1.1.3 seanred.io React version</span></a
				>
			</li>
			<li>
				<a class="hover:opacity-75" href="https://seanred-v-1-1-3-reactversion.netlify.app/"
					><span>V2.2.4 seanred.io Next.js version</span></a
				>
			</li>
		</ul>
	</div>
</footer>

// components/Footer.jsx
import styles from "../styles/Footer.module.scss";
import { Icon } from "@iconify/react";

const Footer = ({ socialMedia, personalInfo }) => {
  const socialMediaMap = socialMedia.map((link) => (
    <span key={link.name}>
      <a href={link.url} target="_blank" rel="noopener noreferrer">
        <Icon icon={link.class} />
      </a>
    </span>
  ));

  return (
    <footer className={styles.footer}>
      <div className={styles["social-links"]}>{socialMediaMap}</div>
      <div className={styles["copyright-group"]}>
        <small>
          Copyright &copy; {personalInfo ? personalInfo.name : "???"}
        </small>
        <br />
        <small>Thanks to my close friend and colleague 纪丽瑶</small>
      </div>
      <div className={styles.archives}>
        <small className={styles.title}>Previous Versions</small>
        <br />
        <br />
        <a
          href="https://seanred-v-1-1-3-reactversion.netlify.app/"
          target="_blank"
          rel="noreferrer"
        >
          V1.1.3 seanred.io React version
        </a>
      </div>
    </footer>
  );
};

export default Footer;
